### ISSUE TITLE
Writting data into SAP ERP

### ISSUE THREAD

**Issue by Akaori** [SAP/PyRFC#102]
Hello, I have a client who uses SAP ERP.

I want to send daily inventory information into his SAP ERP, using python.

Is it possible doing this using PyRFC ?

**Comment by denissa4** [comment]
Yes, it is possible. You can check nlsql.com

**Comment by bsrdjan** [comment]
Technically it is possible, assuming SAP [RFC API for Physical Inventory](https://answers.sap.com/questions/6268846/index.html) provides all functions required in your application,. That is something SAP Functional Consultant for MM could help clarify because I am not familiar with SAP MM API in detail.

Python and PyRFC are in this context "transparent", if the functionality of interest is possible from another ABAP system (via RFC protocol), it is possible from Python as well.

**Comment by Akaori** [comment]
Thanks for helping me
