### ISSUE TITLE
Hint how to create json from connection.call() output

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#119]
I think it is a very common use case to create json from the result which gets returned from `connection.call()`

It would be very kind if you could provide an example in the docs.

This saves time and prevents re-inventing the wheel again and again.

This works:

    import json
    json.dumps(connection.call(rfc_name, **kwargs))

**Comment by mpf82** [comment]
It's very well documented that ``[Connection.call()](http://sap.github.io/PyRFC/pyrfc.html#pyrfc.Connection.call)`` returns a dictionary. 

And looking up "``python dictionary to json``" with a search engine of your choice will yield millions of results.

I don't see how "wheels are being re-invented again and again" here, since a dictionary is a very common data type in python. It's not as if ``Connection.call()`` returns an instance some weird class that cannot be converted to JSON on the fly.

**Comment by guettli** [comment]
A dictionary is just a container. It can contain data which can't be serialized to json. 

If you don't care, I will do the same. I close this.

**Comment by guettli** [comment]
JSON does not support binary data. See #126
