### ISSUE TITLE
Server example is not available in current documentation

### ISSUE THREAD

**Issue by techie-subhadeep** [SAP/PyRFC#148]
Server example is not available in current documentation

 ![Screenshot_20191126_084012](https://user-images.githubusercontent.com/29140664/69596383-6952ed00-1028-11ea-9dca-a49a9e3bd13d.png)

URL : 
https://sap.github.io/PyRFC/server.html

**Comment by bsrdjan** [comment]
Thanks, will be fixed.

**Comment by bsrdjan** [comment]
The example should be completely removed from the documentation, also from the table of content. Did you find the url in the documentation?

**Comment by RonRadtke** [comment]
Is it possible to build a python rfc server with this lib?

**Comment by bsrdjan** [comment]
Yes and one working experimental implementation is provided here:

[pyrfc Server](https://github.com/SAP/PyRFC/blob/dev/src/pyrfc/_pyrfc.pyx#L1084)

[pyrfc Server Test](https://github.com/SAP/PyRFC/blob/dev/material/serverExamples.py)

It works, but experimental and not supported because no capacity for time being to finalize and provide a decent test coverage.

**Comment by bsrdjan** [comment]
Server bindings are implemented in main branch: df9805e

More info: https://github.com/SAP/PyRFC/issues/193#issuecomment-720645607

**Comment by bsrdjan** [comment]
Server bindings are published with 2.3.0 release on PyPI, feel free to test.

**Comment by bsrdjan** [comment]
Documented here: http://sap.github.io/PyRFC/server.html
