### ISSUE TITLE
Date and Time fields not converted to python objects after last change 

### ISSUE THREAD

**Issue by joac** [SAP/PyRFC#15]
After commit [452d36](https://github.com/SAP/PyRFC/commit/452d3684557cbfca96d132fd55ef7b98631bd6fe) on Python 2.7 build, abap fields of type `T` and `D` are returned as strings and not `date` and `time` Python types:

Test:

``` python
from pyrfc import Connection
import datetime

USER = 'an_user'
con = Connection(user=USER, passwd='a_password', 
                 ashost='10.0.0.1', sysnr='00', client='000')
response = con.call('BAPI_USER_GET_DETAIL', USERNAME=USER)

assert isinstance(response['LASTMODIFIED']['MODDATE'], datetime.date)
assert isinstance(response['LASTMODIFIED']['MODTIME'], datetime.time)
```

Please, on the future, change version numbers of builds when doing a fix or change like this.

**Comment by llazzaro** [comment]
Any news on this issue?

**Comment by joac** [comment]
No news from @bsrdjan on the last month...

**Comment by bsrdjan** [comment]
Yes, the version number should be updated but switch from date & time to string was not accidental. SAP  BAPIs and RFC enabled modules use strings for date and time values and when the date/time value is empty in the backend, RFCs return empty string, sometimes of the length zero, sometimes with spaces. That is unfortunately not 100% clean implemented in all BAPIs/RFCs, see the [Issue #6](https://github.com/SAP/PyRFC/issues/6). 

Assume scenario when Python application uses PyRFC to read the date/time field from the backend, using GetDetail BAPI for example and echoes the unchanged value back to backend, using Change BAPI. 

When date/time types used, the original backend string representation of the date (empty/initial) is lost after converting to None in Python. If the date/time is not touched by Python and None sent back, the PyRFC internal logic can convert None to one fixed value, either zero or non-zero length empty string. 
If that value differs from the string sent by GetDetail, some BAPIs return error because they see the date field "changed", from zero to non-zero length for example, without setting the "X-field". 

When strings are used instead of date/time, the backend string representation is propagated to Python (and JavaScript if web application is the use case). If not touched, it is returned "as-is" and BAPIs don't complain. If changed, it is changed to valid date/time (X-Field set) and works.

Using strings basically "covers up" these inconsistencies how BAPIs handle empty dates/times, making less work for PyRFC user or web app programmer. Hope this explanation helps.

**Comment by joac** [comment]
@bsrdjan I think that this behavior (unexpected from my point of view) can be handled this way:
```
If valid date/time -> return date or time
If empty date/time -> return None
If INITIAL date/time -> return INITIAL constant 
```

**Comment by bsrdjan** [comment]
The INITIAL im PyRFC can be one fixed value and backend sends zero or non-zero len strings as INITIAL, the handling therefore does not help.

**Comment by joac** [comment]
Maybe the string can be returned on that cases.

**Comment by bsrdjan** [comment]
The problem is to detect these cases. When PyRFC works wiith None, the original backend value is lost, whether it was zero or non-zero string,.To send the None back, PyRFC csn convert to either zero or non-zero string but can't ensure that matches the original value.

**Comment by Pentusha** [comment]
FYI, 
abap/4 and python uses different calendar implementations. So 2100-02-29 is valid date in abap/4 and not existing and not valid in python.
