### ISSUE TITLE
Make alpha-conversion routines work in PyRFC? [feature-request]

### ISSUE THREAD

**Issue by Suncatcher** [SAP/PyRFC#195]
I want to raise a feature-request about [alpha-routines](https://help.sap.com/viewer/ccc9cdbdc6cd4eceaf1e5485b1bf8f4b/7.40.20/en-US/4a547e956a8a1cd4e10000000a421937.html). Now when I send 1111111 to KUNNR or MATNR, it comes to RFM as 11111111, not like a 0011111111 or 000000000011111111 correspondingly.

Would it be possible to make work automatic conversion per the domain alpha-routine?

**Comment by bsrdjan** [comment]
The RFC protocol does not automatically trigger conversion exits and BAPIs, RFC enabled function modules and external Python (Java, NodeJS ...) programs calling them, always work with internal data representation. More info are given in 2nd point of [206068 - Error when calling a BAPI from an external RFC client](https://launchpad.support.sap.com/#/notes/206068).
 
The RFC connectors can't trigger conversion-exits in automatic and generic way. It is not always needed (data processing programs prefer internal representations) and the solution would require the replication of ABAP conversion-exits logic in connectors. That is not feasible because conversions can be more complicated than add/remove zeroes.

The conversion-exits need to added to RFMs or BAPI wrappers manually, in ABAP backend. Adding one-liner conversions requires very little code and efforts and the biggest challenge was finding all fields relevant for conversions. Now there are at least three methods how to automatically find these fields, described here:

* [fundamental-tools#conversion-exits](https://github.com/SAP/fundamental-tools#conversion-exits) 

* more details: [fundamental-tools/doc/exposure#conversion-exits](https://github.com/SAP/fundamental-tools/tree/master/doc/exposure#conversion-exits)

The generic ABAP conversion example is not supported and I don't see any advantage of using it, over manually added one-liner conversions. Fundamental tools generators could also generate the conversion code but developers' never saw enough value in that because the manual implementation is really simple and fast.

Hope this helps.

**Comment by Suncatcher** [comment]
Thanks for comprehensive explanation. Probably you are right and the implementation not worth it. 

> and the solution would require the replication of ABAP conversion-exits logic in connectors

undoubtedly implementation of each and every routine in the connector is ridiculous. What I am speaking about is somehow through API fetch the routine logic from ERP and run it. Every routine is nothing more than a FM that is easily callable through PyRFC and can be applied to the value in Python. Just a small level of abstraction which won't be that hard to implement.

P.S. As far as I got it from that useful note you gave `BAPI_CONVERSION_EXT2INT` does the same what I am speaking about. Do you have a code snippet for it? Maybe I can create Python function that I can call for each and every call of other RFM?
Though, standard PyRFC implementation of this would be better.

**Comment by bsrdjan** [comment]
> Every routine is nothing more than a FM that is easily callable through PyRFC

The conversion-exits are not remote enabled, thus not callable by connectors. Even if remote enabled, the RFC communication adds the overhead which could be considerable when processing tables with larger data volumes.

`BAPI_CONVERSION_EXT2IN` is not recommended either, as mentioned in [206068 - Error when calling a BAPI from an external RFC client](https://launchpad.support.sap.com/#/notes/206068).

These conversions belong to backend and best/fastest done by ABAP and the method I shared above is based on development experience from many projects. The problem is indeed annoying but easy solvable in ca. one hour for practically any BAPI/RFM. If any issues with the approach, I would be glad to support.

**Comment by Suncatcher** [comment]
> Even if remote enabled, the RFC communication adds the overhead which could be considerable when processing tables with larger data volumes.

the ideal way for large data volumes would be to replicate routine logic in Python and call this Python func for datasets in Python, not in ABAP. Recreation of logic of arbitrary routine will require a big amount of work, and you may consider this level of abstraction redundant and unnecessary, but it is indeed an option.
Beyond any doubt the Python does processing of big data much better than ABAP.

**Comment by bsrdjan** [comment]
The amount of work would be indeed too big for PyRFC project. It would be great if you could describe the feature request in more details and submit via Customer Influence channel: https://launchpad.support.sap.com/#/notes/11 ?

**Comment by bsrdjan** [comment]
The feature request can be created for:

`Security Services` category of the [SAP Cloud Platform – Platform Foundation](https://influence.sap.com/sap/ino/#/campaign/2277)

**Comment by Suncatcher** [comment]
Thanks, I will try to formulate possible implementation

**Comment by bsrdjan** [comment]
Great. Please consider the next review phase starts at Nov 14th. You can also share the link to request here, so that other interested users can find and vote.

**Comment by Suncatcher** [comment]
And which program is more appropriate for this feature-request? Customer Engagement Initiative or Customer Connection? Or any other?
This feature is more related to PyRFC or to NWRFC SDK? In my understanding it can be implemented both on low-level (NWRFC) and in Python too.

**Comment by bsrdjan** [comment]
It is Customer Influence, described in more detail in https://launchpad.support.sap.com/#/notes/11. You can try the [SAP Cloud Platform – Platform Foundation](https://influence.sap.com/sap/ino/#/campaign/2277) link and `Security Services` category.

You are right, the request is related to PyRFC and SAP NWRFC SDK and both implementations could work. The PyRFC however is open source and therefore not covered by Customers Influence. The only way to submit the customer request, for which other customers can also vote, is for SAP NWRFC SDK, via abovementioned campaign. You can also add the "SAP NWRFC SDK" to title.

**Comment by Suncatcher** [comment]
Done
https://influence.sap.com/sap/ino/#/idea/256743
