### ISSUE TITLE
SNCERR_UNKNOWN_MECH  SncPImportPrName() parsing error

### ISSUE THREAD

**Issue by Arjun146** [SAP/PyRFC#203]
HI , 

I am trying to connect to SAP through SSO and got the below error:

**Code**

```python
ABAP_SYSTEM = {
         'snc_partnername': "XXXXXXXXXXXXXXXXXXXXXXXX",
         'snc_lib': 'C:\\Program Files (x86)\\SAP\\SNCEncryption\\x64\\sapsncencryption.dll',

         'name': 'XXX',
         'client': '000',
         'ashost': 'sap00000',
         'sysnr': '00',
         'saprouter': 'SAPROUTER',
         'trace': '3'
        }
```

**Error**

```shell
CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
LOCATION    CPIC (TCP/IP) on local host KKNT-5554842 with Unicode
ERROR       SNCERR_UNKNOWN_MECH
            SncPImportPrName() parsing error
            name="XXXXXXXXXXXXXXXXXXXXXXXX"
TIME        Fri Oct 16 09:43:30 2020
RELEASE     753
COMPONENT   SNC (Secure Network Communication)
VERSION     6
RC          -38
MODULE      D:/depot/bas/753_REL/src/krn/snc/sncxxall.c
LINE        2272
DETAIL      SncPSetNewName
COUNTER     2
 [MSG: class=, type=, number=, v1-4:=;;;]
```
Help here would be highly appreciable.

Thanks,
Arjun

**Comment by bsrdjan** [comment]
Can you connect using SSO with your user, using SAPLogon? Here one documented example you could try with your system:

https://github.com/SAP/node-rfc/blob/master/doc/authentication.md#snc-with-user-pse

**Comment by Arjun146** [comment]
Thank you for your reply bsrdjan.
Yes, I am able to connect to SAP GUI with SSO .. and I followed all the steps mentioned in the document but unfortunately getting the same error

**Comment by bsrdjan** [comment]
No idea what could be the problem here. Could you please describe the setup in more detail:

1. The system landscape? I assume the PyRFC and SNC Lib are installed on standard Windows notebook, from which your script shall SSO connect to ABAP backend. Is that correct?

2. Releases/versions of:
  - Windows:
  - Python:
  - NWRFC SDK
  - SNC Library

Can you create SAP support ticket for BC-MID-RFC-SDK component and share the Python script source code there, with real credentials, that I can check in detail? Please write in a ticket it is related to this issue and add the url: https://github.com/SAP/PyRFC/issues/203

**Comment by Arjun146** [comment]
1. PyRFC is installed but haven't installed SNC Lib, In the code, i am using the path from the SNC_LIB Environment variable. Could you please provide details for installing SNC Lib.

2. Versions 
Python - 3.8.6
Windows - 10
NWRFC SDK -  7.5 Version
SNC Library - Not Installed 

Thanks,
Arjun

**Comment by bsrdjan** [comment]
Hi @Ajrun,

The SNC lib installation and path depend on authentication library used in you organization. If SNC_LIB environment variable is set, the SNC lib should be already installed. Can you check the configuration with your sysadmin of SAP Basis consultant?

The installation steps for SAP Cryptographic Library are described in [SAP Help](https://help.sap.com/viewer/a017d0089ae44f879c89d67dbdafd121/LATEST/en-US/6baad7178e414716a8fe56d91e6556d5.html).

The library used on your system is apparently `sapsncencryption.dll`and SAP crypto lib I am using is `libsapcrypto.dll` but not sure if that difference is important, can't help with SNC configuration.

**Comment by dips4hana** [comment]
@bsrdjan Facing the same error in Eclipse when creating a BW project. Just for info- When we use HANASTUDIO which is installed on a Citrix. I dont have any issues.   But when we use VDI where I have installed latest eclipse, I am getting this error. DWW failed (SNCERR_UNKNOWN_MECH, SncPImportPrName() parsing error, name="p/krb5:SAPServiceDWW/ust2l929.XXX.com@XXX.COM")

Not able to figure out what the issue is but its machine specific .

**Comment by bsrdjan** [comment]
Could you please share (anonymised ) pyrfc connection parameters for connecting to ABAP system?

Eclipse is maybe installing a different version of SAP NWRFC SDK or SCN library but hard to guess without checking the affected system. If you are SAP employee you can send me an Email, to check your configuration.

**Comment by mydoghasfleas** [comment]
Having the same problem with ADT trying to connect to our S/4 system.

It was working up to about a week ago, then suddenly stopped working.

I get this error when trying to log in from ADT or add a new connection:

```
Logon to system XXX failed (SNCERR_UNKNOWN_MECH, SncPImportPrName() parsing error, name="p/secude:CN=xxxxxxx@xxxx.xxx")
```
(Obviously I have just replaced our names with 'xxx')

Connection via SAP GUI works.
