### ISSUE TITLE
calling RKAEP0001 with pyrfc leads to extra screen, blocking output

### ISSUE THREAD

**Issue by arjanbytez** [SAP/PyRFC#204]
I am calling program RKAEP0001 with pyrfc using a valid document number. Code

results = connp.call(
"Z_CM_DATAINT_ECC",
I_REPORT="RKAEP000",
LT_SELECTIONS=[{"SELNAME": "BELNR", "KIND": "S", "SIGN": "I", "OPTION": "EQ", "LOW": "123456789", "HIGH": ""},
{"SELNAME": "P_TCODE", "KIND": "S", "SIGN": "I", "OPTION": "EQ", "LOW": "KABP", "HIGH": ""}] 
)

I have lots of calls like this that do work, but in this case I get an extra screen "You must make an entry" (message text number KB0001). After entering the exact same document number / BELNR as above, I get output as normal.
I'm not sure whether it's a pyrfc thing, but hopefully someone has a pointer to get around this. 

btw the extra tcdode-SELNAME is neccessary because of a hardcoded tcode in a function module (see https://answers.sap.com/questions/6441091/transaction-code-not-defined---reg.html) and is not related.

**Comment by bsrdjan** [comment]
> I have lots of calls like this that do work

"like this" means with slightly different parameters, correct? Or exactly these parameters sometimes work and sometimes not?

I suppose the extra screen is the dialog input screen triggered by ABAP logic, for this particular selection parameters. That should not happen and even with incorrect parameters the error message should be returned, no dialog popup. It looks like the issue with the `Z_CM_DATAINT_ECC` function module ABAP logic and you can check that in ABAP system:

1. Run the transaction SE37 in ABAP system and open the `Z_CM_DATAINT_ECC` function module
2. Enter the `I_REPORT` and `LT_SELECTIONS ` parameters' values, which do not work in Python script
3. Execute the function module from SE37 transaction

If the dialog comes up also when called from ABAP, the function module should be fixed, otherwise we investigate further.

**Comment by arjanbytez** [comment]
> "like this" means with slightly different parameters, correct?

different parameters, correct.

I ran SE37 and entered the exact same parameters. This resulted in the same dialog screen as stated above. So I guess it's not pyrfc-related indeed, and we should go and debug this function module then.

Do you by any chance have a guess as to how we should start debugging it? I know it's not pyrfc-related but I'm not a SAP-developer, and maybe you've encountered issues like this before.

**Comment by bsrdjan** [comment]
You can set the external breakpoint in `Z_CM_DATAINT_ECC`, for the ABAP user running the Python script. When you run the script, the ABAP debugger will show up. Just like described for NodeJS, the same with Python:

[SAP/node-rfc/troubleshooting.md#remote-abap-debugging](https://github.com/SAP/node-rfc/blob/master/doc/troubleshooting.md#remote-abap-debugging)

**Comment by arjanbytez** [comment]
this issue had to do with me not sending off the right transaction code (P_TCODE) to SAP. This resulted in RKAEP000 not receiving the expected input, thereby raising this extra screen (I know all about tcodes now...). Thanks for helping!
