### ISSUE TITLE
LOCATION    CPIC (TCP/IP) on local host 8433780a873b with Unicode on Docker

### ISSUE THREAD

**Issue by galloramiro** [SAP/PyRFC#235]
**Describe the bug**
Hi,
  
Have diferent projects that connect to sap, and some of them repeat the same process.  
  
Now I have a new project that repeat some part of the proces so I migrate this working module to a new project, but its not working.

Its gave me first an impor error, what I solve adding on the docker the `ldconfig`, this command is not necesary in the others docker files that I have.

Now here its the error:
```
*** pyrfc._exception.CommunicationError: RFC_COMMUNICATION_FAILURE (rc=1): key=RFC_COMMUNICATION_FAILURE, message=
LOCATION    CPIC (TCP/IP) on local host 8433780a873b with Unicode
ERROR       partner '{PRIVATE_INFORMATION}.{PRIVATE_INFORMATION}.root:3300' not reached
TIME        Fri Jul  2 11:22:49 2021
RELEASE     753
COMPONENT   NI (network interface)
VERSION     40
RC          -10
MODULE      /bas/753_REL/src/base/ni/nibuf.cpp
LINE        4568
DETAIL      NiBufIConnect: connection pending after 60000ms
SYSTEM CALL connect
ERRNO       115
ERRNO TEXT  Operation now in progress
COUNTER     4
 [MSG: class=, type=, number=, v1-4:=;;;]
```

**To Reproduce**
```
sap_nwrfc_bip_cfg = self._directories_utils.get_sap_cfg_file_path(context_name=__file__, file_name=self._CONFIG_FILE_NAME)
config_parser = ConfigParser()
config_parser.read(sap_nwrfc_bip_cfg)
self._connection: Connection = Connection(**config_parser._sections['connection'])
```
**Screenshots**

**Environment**
 - OS: Linux
 - Running in docker? Yes
 - PyRFC version 
DokcerFile
```
FROM python:3.8-buster
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN apt-get update \
    && apt-get install -y poppler-utils \
    && pip install --upgrade pip


# Install OpenJDK-11
RUN apt-get install -y openjdk-11-jre-headless && \
    apt-get clean;    


# INSTALL PYNWRFC

# configure SAP NW RFC SDK files path
ENV SAPNWRFC_HOME=/usr/local/sap/nwrfcsdk
COPY nwrfc_sdk/nwrfcsdk.conf /etc/ld.so.conf.d/nwrfcsdk.conf

# copy SAP NW RFC SDK files
COPY nwrfc_sdk/nwrfcsdk $SAPNWRFC_HOME

# Install python library dependencies
RUN apt-get install --no-install-recommends \
    gcc \
    g++ \
    && pip --no-cache-dir install https://github.com/SAP/PyRFC/releases/download/v2.4.1/pyrfc-2.4.1-cp38-cp38-linux_x86_64.whl \
    && ldconfig


# Create the workdir
WORKDIR private_folder

CMD mkdir private_folder/src
COPY requirements.txt .
RUN pip install -r requirements.txt

ADD src src
```

In the other projects the only difference is that Im using `python:3.8-slim-buster`, but here because I need to use OpenJDK-11 I use this image.

Hope could help me find the problem, thanks for taking the time to read!

**Comment by bsrdjan** [comment]
Hello @galloramiro and sorry for the delayed response, I was on vacation.

Is it solved on the meantime?

It looks like a network issue because SAP NWRFC SDK is apparently loaded and it tries to connect to ABAP system.

Did you try to capture the detailed trace already, there might be more troubleshooting info there?

If not, could you please add this at the top of `sapnwrfc.ini`, repeat the test and send the recorded trace (trc files):

**sapnwrfc.ini**  

```ini
DEFAULT
RFC_TRACE=3 # 'global' trace level
```

Another possibility might be issues with Unicode, in which case following docker statements may help

```docker
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
```

Python buster should work, as reported in https://github.com/SAP/PyRFC/issues/176#issuecomment-630668873. As a reference you can also check this Python 3.9 buster image working with pyrfc:

[SAP/fundamental-tools/docker/python-39-buster.Dockerfile](https://github.com/SAP/fundamental-tools/blob/main/docker/python-39-buster.Dockerfile)

**Comment by srath2411** [comment]
I am facing the same issue , did it resolve ?
