### ISSUE TITLE
Setting TRACE / RFC_TRACE=3 in destination section of sapnwrfc.ini has no effect

### ISSUE THREAD

**Issue by Tset-Noitamotua** [SAP/PyRFC#26]
I defined a destination in sapnwrfc.ini (which I copied from demo folder of `NWRFC_40-20004568.SAR` as followsJ):

```
DEST=ABC123
ASHOST=ABC123HOSTNAME
SYSNR=123
CLIENT=333
USER=USERNAME
PASSWD=PASSWORD
LANG=DE
RFC_TRACE=3
```

When I run my script no trace file (.trc) is created in current dir.

But when I uncommet line 30 of sapnwrfc.ini so that I have

``` ini
DEFAULT
# Trace all connections/destinations, which do not explicitly define
# their own trace level, with level 1. If this value is not set, the
# default is 0. Possible values are 0(off), 1(brief), 2(verbose), 3(full)
RFC_TRACE=3
```

and then run my script a trace file is created in current dir.

**Comment by bsrdjan** [comment]
the correct parameter name is TRACE, instead of RFC_TRACE.

Variable names in _sapnwrfc.ini_ are for the source code only, irrelevant for the client applications programming. All Connection parameters' names are described in the [SAP NW RFC Programming Guide](https://websmp109.sap-ag.de/~sapidb/011000358700000869672007.pdf), page 17.
