### ISSUE TITLE
import pyrfc fails n Python 3.7

### ISSUE THREAD

**Issue by bsrdjan** [SAP/PyRFC#316]
`import pyrfc` fails with ModuleNotFoundError: No module named 'importlib.metadata', in Python 3.7

**Comment by daniel-aguilar-garcia** [comment]
Hello, is there a way to avoid this error currently?

**Comment by bsrdjan** [comment]
Did you try manual install:

```shell
pip install importlib-metadata
```

**Comment by s1lvester** [comment]
Manual installation won't work for 3.7

importlib.metadata is only available since python 3.8 so:

`from importlib import metadata`

will always fail on 3.7.

Since this was introduced in 2.8.3, maybe @bsrdjan should pull that release from pypi and only supply wheels for 2.8.2 (which works with 3.7) and  anything > 3.0 requires python 3.8

**Comment by bsrdjan** [comment]
fixed by v2.8.31
