### ISSUE TITLE
Timeout doesn't work

### ISSUE THREAD

**Issue by unitythemaker** [SAP/PyRFC#328]
**Describe the bug**
None of the timeout options work. Both of these https://github.com/SAP/PyRFC/tree/main/examples/timeout examples waits 60 seconds to tell me "NiBufIConnect: connection pending after 60000ms".

**To Reproduce**
I am just running these and they wait 60 seconds instead of waiting 5 or 10 seconds: https://github.com/SAP/PyRFC/tree/main/examples
The only thing I've edited is that I removed dest and instead of dest, I am using ashost=ASHOST, sysnr=SYSNR, client=CLIENT, user=USER, passwd=PASSWD options.

**Screenshots**
![2023-07-17_23-52](https://github.com/SAP/PyRFC/assets/83316880/0fa493a9-c622-4cb4-9c02-9288f4e3aca4)

**Environment**
 - OS: Linux
 - Running in docker? Yes
 - PyRFC version: Both tested on 2.7.0 and 3.0.0 with Python versions 3.9 and 3.10

**Additional context**
I can include any other data if you request from me.

**Comment by unitythemaker** [comment]
Okay so I just discovered that it wouldn't work with 2.7.0 because timeout feature is added in 2.8.0 version but it still doesn't work with v3.0.0

**Comment by bsrdjan** [comment]
The error message is telling that connection with ABAP system could not be established. Standard timeout when waiting for connection is 60 sec and that is ABAP system setting. Because the connection is not open, the PyRFC RFC call with timeout is not executed at all.

There is either a network error or error in your PyRFC connection parameters. When that is resolved the timeout should work.
