### ISSUE TITLE
Issue with TIMS data type conversion

### ISSUE THREAD

**Issue by dbaranasic** [SAP/PyRFC#336]
**Describe the bug**
I am running RFC server with PyRFC. Sometimes, when registered function is triggered I get parse error. From SAP, we are sending the data with structure BAPI_ORDER_HEADER1 to RFC Server.    

**To Reproduce**
The error occurs as soon as any of TIMS (time) data type value (for example SCHED_START_TIME) is set to 240000 (24:00:00). 
If I change the value to 000000, then there is no error. 

**Screenshots**
![mRemoteNG_ZfaNfUuR0n](https://github.com/SAP/PyRFC/assets/145329736/af7924b6-cad8-423d-aa01-0835f02a801c)

**Environment**
 - OS: Windows 10 VM
 - Python 3.11.2
 - PyRFC 2.7.1
 - SAP 2019 on premise 

**Additional context**
Tested also with PyRFC 3.1 (in this case there was no error, but also registered function was not called at all)

**Comment by bsrdjan** [comment]
It is a bug, caused by not passing the date/time handling configuration to server. The standard configuration returns DATE and TIMS ABAP fields as strings. Here the server tries to create the Python datetime object from "240000" and fails. It should just pass the ABAP string as-is, without interpretation. The fix should be available early next week.

**Comment by bsrdjan** [comment]
Hello @dbaranasic,

new server configuration options are added in release 3.2, so that strict TIMS value check can be disabled. 
When set to `False`, like in [this example](https://github.com/SAP/PyRFC/blob/main/examples/server/server_pyrfc_thread.py#L42), the Python server will not complain about ABAP TIMS values out of standard range:

```python
server = Server(
    {"dest": "MME_GATEWAY"},
    {"dest": "MME"},
    {"check_time": False, "server_log": True}
)
```

Could you please test and re-open, if any issues.

**Comment by dbaranasic** [comment]
@bsrdjan thanks, I will test it out.
